apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  # 主题id，唯一
  name: theme-dream-fixed
spec:
  # 主题名称
  displayName: Dream Fixed
  author:
    # 作者名称
    name: nineya ＆ pzwboy
    # 作者网址
    website: https://pzwboy.top
  # 主题描述
  description: '梦之城，童话梦境'
  # 主题logo地址
  logo: /themes/theme-dream-fixed/assets/img/logo.png
  # 主题地址
  homepage: https://github.com/pzwboy/halo-theme-dream2.0-fixed
  # 主题github开源地址
  repo: https://github.com/pzwboy/halo-theme-dream2.0-fixed.git
  settingName: theme-dream-setting
  configMapName: theme-dream-configMap
  # 版本号
  version: 1.0.0
  # 最低支持的 Halo 版本
  requires: ">=2.0.0"
  
  issues: https://github.com/pzwboy/halo-theme-dream2.0-fixed/issues